## 1. Importación de librerías

En este bloque se importan las librerías necesarias para el procesamiento de datos.  
`pandas` se utiliza para la lectura y manipulación de archivos CSV, mientras que `builtins` permite usar la función `print` estándar dentro del entorno de Jupyter Notebook.


## 2. Carga de bases de datos meteorológicas

Este bloque lee cinco archivos CSV correspondientes a diferentes grupos de variables meteorológicas de la localidad **Santa Fe**.  
Se utiliza el parámetro `skiprows` para omitir las filas iniciales que contienen metadatos y no forman parte de la tabla de datos.



## 3. Agrupación de los DataFrames en una lista

En este bloque se almacenan todos los DataFrames en una lista para facilitar su recorrido y visualización mediante un bucle.



## 4. Visualización preliminar de los conjuntos de datos

Este bloque recorre cada DataFrame y muestra:
- Las primeras cinco filas (`head()`), para inspeccionar la estructura de los datos.
- Las dimensiones del conjunto de datos (`shape`), indicando número de filas y columnas.

Esto permite realizar una validación inicial de la correcta carga de los archivos y una exploración básica de su estructura.

In [ ]:
import pandas as pd
import builtins

df1 = pd.read_csv(r"C:\Users\Xiomara\Documents\Projects\Tesis\cd_tesis\Par_meteo\raw_db\Santa Fe\Humidity_Precipitation_Santa.csv", skiprows=14)
df2 = pd.read_csv(r"C:\Users\Xiomara\Documents\Projects\Tesis\cd_tesis\Par_meteo\raw_db\Santa Fe\Soil_Properties_Santa.csv", skiprows=11)
df3 = pd.read_csv(r"C:\Users\Xiomara\Documents\Projects\Tesis\cd_tesis\Par_meteo\raw_db\Santa Fe\Temperature_Thermal_Santa.csv", skiprows=16)
df4 = pd.read_csv(r"C:\Users\Xiomara\Documents\Projects\Tesis\cd_tesis\Par_meteo\raw_db\Santa Fe\Wind_Pressure_Santa.csv", skiprows=19)
df5 = pd.read_csv(r"C:\Users\Xiomara\Documents\Projects\Tesis\cd_tesis\Par_meteo\raw_db\Santa Fe\Solar_Fluxes_and_Related_Santa.csv", skiprows=20)

datasets = [df1, df2, df3, df4, df5]

for i, df in enumerate(datasets, start=1):
    builtins.print(f"\n--- DATASET {i} ---")
    display(df.head())
    builtins.print(df.shape)

--- DATASET 1 ---

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,ALLSKY_SFC_LW_DWN,2020,31.45,31.78,32.74,32.62,32.56,31.87,31.94,32.02,32.20,32.19,32.21,32.08,32.14
1,ALLSKY_SFC_LW_DWN,2021,31.83,33.35,33.06,32.29,32.28,31.90,31.94,32.09,31.99,32.28,31.96,32.30,32.27
2,ALLSKY_SFC_LW_DWN,2022,31.90,32.56,32.51,33.42,32.98,32.95,32.91,32.53,33.11,33.09,33.04,32.59,32.80
3,ALLSKY_SFC_LW_DWN,2023,32.45,32.87,33.71,33.32,33.15,32.73,33.16,33.11,33.52,33.66,33.53,33.61,33.24
4,ALLSKY_SFC_LW_DWN,2024,32.78,34.25,34.67,34.04,33.94,33.44,33.04,33.09,33.66,33.33,33.50,33.62,33.61

(30, 15)

--- DATASET 2 ---

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,GWETPROF,2020,0.73,0.68,0.68,0.68,0.69,0.74,0.75,0.72,0.71,0.65,0.63,0.59,0.69
1,GWETPROF,2021,0.62,0.60,0.61,0.64,0.63,0.63,0.63,0.59,0.57,0.56,0.56,0.54,0.60
2,GWETPROF,2022,0.51,0.51,0.58,0.65,0.74,0.79,0.79,0.80,0.76,0.78,0.83,0.81,0.71
3,GWETPROF,2023,0.80,0.76,0.76,0.80,0.82,0.82,0.80,0.75,0.71,0.72,0.75,0.72,0.77
4,GWETPROF,2024,0.68,0.61,0.56,0.58,0.71,0.79,0.80,0.73,0.65,0.65,0.70,0.70,0.68

(15, 15)

--- DATASET 3 ---

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,ALLSKY_SFC_LW_DWN,2020,31.45,31.78,32.74,32.62,32.56,31.87,31.94,32.02,32.20,32.19,32.21,32.08,32.14
1,ALLSKY_SFC_LW_DWN,2021,31.83,33.35,33.06,32.29,32.28,31.90,31.94,32.09,31.99,32.28,31.96,32.30,32.27
2,ALLSKY_SFC_LW_DWN,2022,31.90,32.56,32.51,33.42,32.98,32.95,32.91,32.53,33.11,33.09,33.04,32.59,32.80
3,ALLSKY_SFC_LW_DWN,2023,32.45,32.87,33.71,33.32,33.15,32.73,33.16,33.11,33.52,33.66,33.53,33.61,33.24
4,ALLSKY_SFC_LW_DWN,2024,32.78,34.25,34.67,34.04,33.94,33.44,33.04,33.09,33.66,33.33,33.50,33.62,33.61

(40, 15)

--- DATASET 4 ---

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,PS,2020,82.34,82.33,82.35,82.39,82.40,82.40,82.36,82.36,82.34,82.29,82.29,82.25,82.34
1,PS,2021,82.22,82.23,82.26,82.28,82.38,82.42,82.43,82.40,82.39,82.32,82.27,82.24,82.32
2,PS,2022,82.28,82.24,82.27,82.28,82.39,82.38,82.39,82.38,82.36,82.34,82.31,82.26,82.32
3,PS,2023,82.34,82.28,82.33,82.30,82.37,82.40,82.41,82.39,82.33,82.33,82.28,82.27,82.34
4,PS,2024,82.35,82.35,82.34,82.33,82.36,82.41,82.42,82.44,82.34,82.35,82.28,82.27,82.35

(55, 15)

--- DATASET 5 ---

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,ALLSKY_SFC_PAR_TOT,2020,8.89,9.07,7.76,7.91,7.73,7.96,7.92,7.89,8.79,8.28,7.67,8.24,8.17
1,ALLSKY_SFC_PAR_TOT,2021,8.59,7.81,7.16,7.97,8.43,8.12,8.05,8.04,8.66,8.46,8.54,7.99,8.15
2,ALLSKY_SFC_PAR_TOT,2022,8.32,7.47,7.74,7.55,7.90,7.34,7.70,8.32,8.27,8.46,7.72,8.57,7.95
3,ALLSKY_SFC_PAR_TOT,2023,7.99,8.71,7.14,7.39,8.29,8.36,8.12,8.56,8.69,8.41,7.88,7.70,8.10
4,ALLSKY_SFC_PAR_TOT,2024,9.40,8.34,7.67,8.06,7.52,7.77,8.23,8.49,8.38,9.06,7.48,7.58,8.17

(60, 15)

## 5. Unión de los conjuntos de datos

En este bloque se integran los cinco DataFrames previamente cargados en un único conjunto de datos denominado `df_total`.  
La función `pd.concat()` permite combinar los DataFrames de forma vertical (por filas), mientras que el parámetro `ignore_index=True` reinicia el índice para mantener una numeración continua y evitar duplicados en el índice.

Este procedimiento facilita el análisis conjunto de todas las variables meteorológicas en una sola estructura de datos.

In [8]:
# unirlos
df_total = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)

## 6. Asignación de información geográfica y verificación de la estructura del DataFrame

En este bloque se incorporan nuevas columnas al conjunto de datos consolidado (`df_total`) para identificar la localidad y su ubicación geográfica:
- `localidad`: nombre de la localidad asociada a los registros.
- `latitud`: coordenada geográfica en grados decimales.
- `longitud`: coordenada geográfica en grados decimales.

Posteriormente, se realiza una verificación básica de la estructura del DataFrame mediante:
- `head()`, para visualizar las primeras filas.
- `type()`, para confirmar el tipo de objeto.
- `shape`, para identificar el número de filas y columnas.

Este paso permite validar que la información geográfica fue añadida correctamente y que el conjunto de datos mantiene una estructura adecuada para su posterior análisis.

In [9]:
df_total["localidad"] = "Santa Fe"
df_total["latitud"] = 4.60947
df_total["longitud"] = -74.08135
df_total.head()
type(df_total)
df_total.shape

(200, 18)

## 7. Identificación de valores nulos en el conjunto de datos

En este bloque se evalúa la presencia de valores faltantes en cada columna del DataFrame consolidado (`df_total`).  
La función `isnull().sum()` permite contabilizar el número de valores nulos por variable, lo que facilita la detección de posibles problemas de calidad de datos.

Este procedimiento es fundamental para definir estrategias posteriores de limpieza y tratamiento de datos incompletos, tales como eliminación de registros o imputación de valores.

In [10]:
print(df_total.isnull().sum())

PARAMETER    0
YEAR         0
JAN          0
FEB          0
MAR          0
APR          0
MAY          0
JUN          0
JUL          0
AUG          0
SEP          0
OCT          0
NOV          0
DEC          0
ANN          0
localidad    0
latitud      0
longitud     0
dtype: int64

## 8. Almacenamiento del conjunto de datos procesado

En este bloque se exporta el DataFrame consolidado y procesado (`df_total`) a un archivo CSV denominado `base_limpia_Santa.csv`, el cual se guarda en la carpeta de salida destinada a las bases de datos depuradas (`processed_db`).  
El parámetro `index=False` evita que se incluya la columna de índice en el archivo final.

Posteriormente, se visualizan las primeras filas del conjunto de datos mediante `head()`, con el fin de verificar que la exportación se haya realizado correctamente y que la estructura del archivo sea coherente con los datos procesados.

In [ ]:
# guardar archivo limpio
df_total.to_csv(
    r"C:\Users\Xiomara\Documents\Projects\Tesis\cd_tesis\Par_meteo\processed_db\base_limpia_Santa.csv",
    index=False
)
df_total.head()

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN,localidad,latitud,longitud
0,ALLSKY_SFC_LW_DWN,2020,31.45,31.78,32.74,32.62,32.56,31.87,31.94,32.02,32.20,32.19,32.21,32.08,32.14,Santa Fe,4.60947,-74.08135
1,ALLSKY_SFC_LW_DWN,2021,31.83,33.35,33.06,32.29,32.28,31.90,31.94,32.09,31.99,32.28,31.96,32.30,32.27,Santa Fe,4.60947,-74.08135
2,ALLSKY_SFC_LW_DWN,2022,31.90,32.56,32.51,33.42,32.98,32.95,32.91,32.53,33.11,33.09,33.04,32.59,32.80,Santa Fe,4.60947,-74.08135
3,ALLSKY_SFC_LW_DWN,2023,32.45,32.87,33.71,33.32,33.15,32.73,33.16,33.11,33.52,33.66,33.53,33.61,33.24,Santa Fe,4.60947,-74.08135
4,ALLSKY_SFC_LW_DWN,2024,32.78,34.25,34.67,34.04,33.94,33.44,33.04,33.09,33.66,33.33,33.50,33.62,33.61,Santa Fe,4.60947,-74.08135